CREATE TABLE USER_PROFILE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    AGE INT,
    JOB VARCHAR(100),
    LOCATION VARCHAR(100) NOT NULL,
    GENDER VARCHAR(20),
    RELATIONSHIP_STATUS VARCHAR(20),
    BIRTH_DATE DATE,
    MODIFICATION_DATE DATETIME,
    CREATION_DATE DATETIME
);

CREATE TABLE INTERACTION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    INTERACTION_DATE DATETIME,
    INTERACTION_TYPE VARCHAR(20),
    SRC_USER_PROFILE_ID INT,
    DEST_USER_PROFILE_ID INT,
    FOREIGN KEY (SRC_USER_PROFILE_ID) REFERENCES USER_PROFILE(ID),
    FOREIGN KEY (DEST_USER_PROFILE_ID) REFERENCES USER_PROFILE(ID)
);

CREATE TABLE FRAUDULENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_PROFILE_ID INT,
    CREATION_DATE DATETIME,
    FOREIGN KEY (USER_PROFILE_ID) REFERENCES USER_PROFILE(ID)
);